### ISSUE TITLE
Connect blows up if INFO message is greater than 1024 bytes.

### ISSUE THREAD

**Issue by charliestrawn** [nats-io/python-nats#19]
Currently we have a fairly large gnatsd cluster (16+ nodes). This causes the INFO message returned when trying to connect to be larger than [1KB which prevents us from connecting](https://github.com/nats-io/python-nats/blob/master/nats/io/client.py#L570). We are working on reducing our nodes to a saner number, but it doesn't look like the other languages have this limitation. Is there a reason for this limit or can it be removed?

**Comment by wallyqs** [comment]
Hi @charliestrawn, yes this constraint can be removed so that connect can work in that case. Server now allows to bump the size of the maximum control line for example, so client needs to allow reading of larger protocol lines from other commands too.
https://github.com/nats-io/gnatsd/blob/8f52f53a906e2cf91a250229de47eede73680a1a/server/configs/test.conf#L32

**Comment by wallyqs** [comment]
Fixed via #20

**Comment by wallyqs** [comment]
Hi @charliestrawn, just did a bug fix release v0.5.2 where this constraint is removed.

**Comment by charliestrawn** [comment]
Thanks @wallyqs and @petemiron! Insanely great turnaround time.
